name: py310
channels:
  - pytorch
  - huggingface
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - accelerate=0.19.0
  - aiohttp=3.8.1
  - aiosignal=1.3.1
  - ansiwrap=0.8.4
  - arrow-cpp=11.0.0
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - attrs=23.1.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=23.3.0
  - blas=1.0
  - bleach=4.1.0
  - boost-cpp=1.65.1
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=39.0.1
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.1.105
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.1.105
  - cuda-nsight-compute=12.1.1
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.1.105
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.1.105
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.1.105
  - cuda-runtime=11.6.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.1.105
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - dataclasses=0.8
  - datasets=2.12.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.6
  - entrypoints=0.4
  - executing=1.2.0
  - filelock=3.9.0
  - frozenlist=1.3.3
  - fsspec=2023.5.0
  - gds-tools=1.6.1.9
  - gflags=2.2.2
  - glog=0.5.0
  - grpc-cpp=1.46.1
  - huggingface_hub=0.14.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.0
  - ipython=8.13.2
  - ipywidgets=8.0.6
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.1.1
  - jupyter_client=7.3.4
  - jupyter_core=4.12.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=3.0.7
  - keyutils=1.6.1
  - krb5=1.19.3
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.6.1.9
  - libcufile-dev=1.6.1.9
  - libcurand=10.3.2.106
  - libcurand-dev=10.3.2.106
  - libcurl=7.87.0
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libnghttp2=1.46.0
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libuuid=1.41.5
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - multiprocess=0.70.14
  - mypy_extensions=1.0.0
  - nbconvert=6.5.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nsight-compute=2023.1.1.4
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=1.1.1t
  - orc=1.7.4
  - packaging=23.1
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - papermill=2.3.4
  - parso=0.8.3
  - pathspec=0.11.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=2.6.2
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-xxhash=3.0.0
  - python_abi=3.10
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - pytz=2023.3
  - pyyaml=6.0
  - pyzmq=25.0.2
  - re2=2022.04.01
  - readline=8.2
  - regex=2022.7.9
  - requests=2.29.0
  - sacremoses=master
  - scikit-learn=1.0.2
  - scipy=1.8.1
  - sentencepiece=0.1.99
  - setuptools=66.0.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tenacity=8.2.2
  - textwrap3=0.9.2
  - threadpoolctl=3.1.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tokenizers=0.11.4
  - tomli=2.0.1
  - tornado=6.1
  - tqdm=4.65.0
  - traitlets=5.9.0
  - transformers=4.28.1
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - utf8proc=2.6.1
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - wheel=0.38.4
  - widgetsnbextension=4.0.7
  - xxhash=0.8.0
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - beautifulsoup4==4.12.2
    - evaluate==0.4.0
    - fastjsonschema==2.17.1
    - jsonschema==4.17.3
    - nbclient==0.8.0
    - nbformat==5.9.0
    - pyrsistent==0.19.3
    - responses==0.18.0
    - soupsieve==2.4.1
prefix: /home/yjunteng/anaconda3/envs/py310
